[package]
name = "Achernar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webbrowser = "0.8.2"
clap = { version="4.0.8", features=["derive"]}
egui = "0.20.1"
tracing = "0.1.37"
eframe = "0.20.1"
tracing-subscriber = "0.3.15"
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
tempfile = "3.3.0"
self_update = "0.39.0"
